import type { NextPage } from "next";
import Head from "next/head";
import { request, gql } from "graphql-request";

export async function getServerSideProps() {
  const query = gql`
    {
      frameworks {
        id
        name
      }
    }
  `;
  const data: any = await request("http://localhost:3000/api/graphql", query);
  const { frameworks } = data;
  return {
    props: {
      frameworks,
    },
  };
}

const Home: NextPage = ({ frameworks }: any) => {
  return (
    <>
      <Head>
        <title>Nextjs Flashcards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <ul>
          {frameworks.map((f: any) => (
            <li key={f.id} className="text-3xl text-green-600 ">
              {f.name}
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
